//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItem_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<int> Drink_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual Order Order { get; set; }
    }
}
